### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/bilfeldt/laravel-http-client-logger/pull/16/commits/23df6eeb10654de420d5b099aa882587052e735b?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-http-client-logger.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "bilfeldt/laravel-http-client-logger": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by bilfeldt** [comment]
Currently awaiting approval of https://github.com/timacdonald/log-fake/pull/32

**Comment by lionslair** [comment]
Did you just run a normal laravel shift 8-9 to produce this? Didn't know shift works on packages.

**Comment by bilfeldt** [comment]
> Did you just run a normal laravel shift 8-9 to produce this? Didn't know shift works on packages.

No actually Shift made it automatically without my request: https://twitter.com/laravelshift/status/1490709249491714050?s=21

I assume they made them for packages used in projects that have used a paid shift.

**Comment by jasonmccreary** [comment]
@lionslair, @bilfeldt, they are collected from our [Can I Upgrade Laravel](https://caniupgradelaravel.com/) tool.

It is offered to help community packages prepare for new releases of Laravel.

**Comment by lionslair** [comment]
That Did a pr though. Hmm interesting. If you have code incompatibility will it fix that or just the composer file

**Comment by jasonmccreary** [comment]
@lionslair, its focus is mostly on compatibility. Future runs may try to analyze the code too.

**Pull request merged**
